Re-enable MySQL test, partially fix it and add extra logging
The data-integrator returns 'endpoints' as 'hostname' for MySQL
and as 'IP' for postgresql:

> juju run-action data-integrator/0 get-credentials
> ...
>     mysql:
>       endpoints: juju-cab1f5-1:3306
> ...
>     postgresql:
>       endpoints: 10.234.188.136:5432

as a result the test cannot connect MySQL to create a test data:

> Traceback (most recent call last):
>   File "/home/taurus/canonical/data-integrator/tests/integration/test_charm.py", line 94, in test_deploy_and_relate_mysql
>     with MysqlConnector(config) as cursor:
>   File "/home/taurus/canonical/data-integrator/tests/integration/connector.py", line 29, in __enter__
>     self.connection = mysql.connector.connect(**self.config)
>   File "/home/taurus/canonical/data-integrator/.tox/integration/lib/python3.10/site-packages/mysql/connector/pooling.py", line 286, in connect
>     return CMySQLConnection(*args, **kwargs)
>   File "/home/taurus/canonical/data-integrator/.tox/integration/lib/python3.10/site-packages/mysql/connector/connection_cext.py", line 101, in __init__
>     self.connect(**kwargs)
>   File "/home/taurus/canonical/data-integrator/.tox/integration/lib/python3.10/site-packages/mysql/connector/abstracts.py", line 1108, in connect
>     self._open_connection()
>   File "/home/taurus/canonical/data-integrator/.tox/integration/lib/python3.10/site-packages/mysql/connector/connection_cext.py", line 273, in _open_connection
>     raise get_mysql_exception(
> mysql.connector.errors.DatabaseError: 2005 (HY000): Unknown MySQL server host 'juju-eacd83-1' (-3)

Also it is not possible to resolve 'juju-eacd83-1' into the IP as
it is an internal juju name which is not resolvable from test env.